apiVersion: apps/v1
kind: Deployment
metadata:
  name: mission-link-deployment
  labels:
    app: mission-link
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mission-link
  template:
    metadata:
      labels:
        app: mission-link
    spec:
      containers:
      - name: mission-link
        image: 257840391579.dkr.ecr.ap-northeast-2.amazonaws.com/final:20230621084718
        ports:
        - containerPort: 3000