apiVersion: v1
kind: Service
metadata:
  name: mission-link-service
spec:
  selector:
    app: mission-link
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer